name: Vite React CI/CD Pipeline

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main # Trigger on pull requests to the main branch

jobs:
  build_and_deploy: # Renamed job to reflect direct deployment
    name: Build and Deploy React App
    runs-on: ubuntu-latest # Use the latest Ubuntu environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Action to checkout your repository code

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24' # IMPORTANT: Specify the Node.js version you use (e.g., '18', '20', '22')
        cache: 'npm' # Cache npm dependencies for faster builds

    - name: Install dependencies
      run: npm ci # 'npm ci' for clean install in CI environments

    # Removed the 'Run tests' step as it was causing the "Missing script: test" error.
    # If you add testing later (e.g., with Vitest), re-enable this step after configuring your package.json.

    - name: Build React App (Vite)
      run: npm run build # Vite build command, outputs to 'dist' folder

    # --- Deployment to Hostinger via FTP/SFTP ---
    # This step uses the built artifacts directly without a separate upload/download artifact step.
    # This simplifies the workflow for direct deployment.
    - name: Deploy via FTP/SFTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.0 # A popular GitHub Action for FTP deployment
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: sftp # Recommended protocol for Hostinger for secure transfer
        local-dir: ./dist/ # IMPORTANT: Deploy from the 'dist' folder
        # remote-dir: /public_html/ # Your target directory on Hostinger. Adjust if deploying to a subdomain or subdirectory.
        # Example for a subdirectory: remote-dir: /public_html/my-react-app/
        # Example for a subdomain (e.g., blog.yourdomain.com): remote-dir: /domains/blog.yourdomain.com/public_html/
        remote-dir: /public_html/ # **IMPORTANT: Verify this path with your Hostinger File Manager**
        delete-excluded: false # Set to 'false' if your .htaccess is outside 'dist' and you don't want it deleted.
                               # If your .htaccess is copied INTO 'dist' by Vite config, you can set this to 'true'.
        dangerous-clean-slate: false # Always keep this as 'false' unless you fully understand the risks.
