name: Vite React CI/CD Pipeline

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main # Trigger on pull requests to the main branch

jobs:
  build_and_deploy:
    name: Build and Deploy React App
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Confirm your Node.js version here
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build React App (Vite)
      run: npm run build

    # --- Deployment to Hostinger via SFTP (Recommended for Hostinger) ---
    - name: Deploy via SFTP
      # CHANGED: Using a different action that supports SFTP
      uses: secretory/action-sftp-deploy@v1.4.0 # A robust SFTP deployment action
      with:
        host: ${{ secrets.FTP_SERVER }}      # CHANGED: 'server' is now 'host'
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 22                             # ADDED: Default SFTP port (22). Confirm with Hostinger if different.
        localDir: ./dist/                    # CHANGED: 'local-dir' is now 'localDir'
        remoteDir: /public_html/             # CHANGED: 'server-dir' is now 'remoteDir' (or 'deploy_path' in some actions)
                                             # **IMPORTANT: Verify this path with your Hostinger File Manager**
        # exclude: "**.git*"                 # Optional: Exclude patterns (if needed)
        # delete-remote-files: true          # Optional: Delete files on remote that are not in local. Use with CAUTION!
                                             # Consider leaving this commented out or 'false' if your .htaccess is not in 'dist'.
                                             # If you use this, also add: args: --delete --checksum --verbose
